// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTKeqEd9WjgshRO-MYpjcu1l0Acnr6M78',
    appId: '1:390200307747:web:cb5fa1d00f91b272634196',
    messagingSenderId: '390200307747',
    projectId: 'buburku-4a056',
    authDomain: 'buburku-4a056.firebaseapp.com',
    storageBucket: 'buburku-4a056.firebasestorage.app',
    measurementId: 'G-MSGF6XZTB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaZ4Lt-GJNA6FGsVTCQVEG7ftcpgwNDSY',
    appId: '1:390200307747:android:8587d7d76e86abfb634196',
    messagingSenderId: '390200307747',
    projectId: 'buburku-4a056',
    storageBucket: 'buburku-4a056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUl-IAScUvi1sS7tBrCftjoAygNs1lMU0',
    appId: '1:390200307747:ios:b3c8e5b36e6ac3de634196',
    messagingSenderId: '390200307747',
    projectId: 'buburku-4a056',
    storageBucket: 'buburku-4a056.firebasestorage.app',
    iosBundleId: 'com.example.buburku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUl-IAScUvi1sS7tBrCftjoAygNs1lMU0',
    appId: '1:390200307747:ios:b3c8e5b36e6ac3de634196',
    messagingSenderId: '390200307747',
    projectId: 'buburku-4a056',
    storageBucket: 'buburku-4a056.firebasestorage.app',
    iosBundleId: 'com.example.buburku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTKeqEd9WjgshRO-MYpjcu1l0Acnr6M78',
    appId: '1:390200307747:web:f6a58ab68c6a4576634196',
    messagingSenderId: '390200307747',
    projectId: 'buburku-4a056',
    authDomain: 'buburku-4a056.firebaseapp.com',
    storageBucket: 'buburku-4a056.firebasestorage.app',
    measurementId: 'G-627W8VCW3V',
  );
}
